// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      // case TargetPlatform.windows:
      //   return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMU6oltBkpVzNJcpkCJKLk9gCMFPzIMuY',
    appId: '1:273314792235:web:f8313e0da89a624e58fb6e',
    messagingSenderId: '273314792235',
    projectId: 'doconnect-b45a9',
    authDomain: 'doconnect-b45a9.firebaseapp.com',
    storageBucket: 'doconnect-b45a9.appspot.com',
    measurementId: 'G-Y0TCC4XCXP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUYAiOtdEkXMouuJhwVAABcLdfJ0xxkQc',
    appId: '1:273314792235:android:8fdbf48181ed8fed58fb6e',
    messagingSenderId: '273314792235',
    projectId: 'doconnect-b45a9',
    storageBucket: 'doconnect-b45a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRZXrhyEyDazEb5lyVHvwtrEeyYAhLzCQ',
    appId: '1:273314792235:ios:d741253abd2e313458fb6e',
    messagingSenderId: '273314792235',
    projectId: 'doconnect-b45a9',
    storageBucket: 'doconnect-b45a9.appspot.com',
    androidClientId: '273314792235-9c0jsvbvlhfrj3cdnsskfaai98n6s0kt.apps.googleusercontent.com',
    iosClientId: '273314792235-3vl5p13rs7oouodjv10uc2k394khrig8.apps.googleusercontent.com',
    iosBundleId: 'com.example.doconnect',
  );

  // static const FirebaseOptions windows = FirebaseOptions(
  //   apiKey: 'AIzaSyANYgpPxx82HKD8I3S-tayrYP-IVAZC6qU',
  //   appId: '1:1082814269313:web:40c7abd4385579fb68ca80',
  //   messagingSenderId: '1082814269313',
  //   projectId: 'medlink-aa15b',
  //   authDomain: 'medlink-aa15b.firebaseapp.com',
  //   storageBucket: 'medlink-aa15b.appspot.com',
  //   measurementId: 'G-T6NZHWLP1N',
  // );

}